[program:horizon-prod]
process_name=%(program_name)s
command=php /home/twoclicks.com.br/twoclicksdocs/artisan horizon
directory=/home/twoclicks.com.br/twoclicksdocs
user=deployer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/home/twoclicks.com.br/twoclicksdocs/storage/logs/horizon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=HOME="/home/deployer",USER="deployer",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
